#ifndef ELKE_CONFIGURATION_H
#define ELKE_CONFIGURATION_H

#define PROJECT_VERSION       "0.0.1"
#define PROJECT_MAJOR_VERSION 0
#define PROJECT_MINOR_VERSION 0
#define PROJECT_PATCH_VERSION 1

#endif
